# pdf_generate.py
import os
import re
import qrcode
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Image, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.platypus.flowables import HRFlowable

class NumberedCanvas(canvas.Canvas):
    """
    Custom canvas that performs two-pass rendering to dynamically compute
    and display the total page count, running headers, and running footers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#7F8C8D"))
        
        # Header (Pages 2 and later)
        if self._pageNumber > 1:
            self.setLineWidth(0.5)
            self.setStrokeColor(colors.HexColor("#BDC3C7"))
            self.line(54, 785, 541, 785)
            self.drawString(54, 792, "TrekFlow Pro Max — Interactive Travel Itinerary")
            
        # Footer (All pages)
        self.setLineWidth(0.5)
        self.setStrokeColor(colors.HexColor("#BDC3C7"))
        self.line(54, 55, 541, 55)
        self.drawString(54, 42, "Generated by AI Trip Planner Co-Pilot")
        self.drawRightString(541, 42, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


# Regex to strip emojis and non-standard symbols that Helvetica cannot render
emoji_pattern = re.compile(
    "["
    "\U00010000-\U0010ffff"  # Emojis/Non-BMP characters
    "\u2600-\u27bf"          # Dingbats & Misc symbols
    "\u2b50"                 # Star emoji
    "]+", flags=re.UNICODE
)

def clean_txt(t):
    """Strips emoji characters and double bullet icons from input text."""
    if not t:
        return ""
    t = emoji_pattern.sub("", t)
    # Remove styling/bullet relics
    t = t.replace("■", "").replace("✨", "").replace("🟦", "").replace("•", "").replace("👉", "").strip()
    return t

def escape_xml(t):
    """Cleans text and escapes HTML/XML special entities for ReportLab Paragraph."""
    t = clean_txt(t)
    t = t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Convert markdown bold to HTML bold tags
    t = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", t)
    return t


def generate_pdf(itinerary_text, filename="trip.pdf", qr_url=None, weather_data=None, trip_type="Solo", num_people=1, total_budget=15000, start_date=None, end_date=None):
    """
    Generates a beautifully styled, structured travel itinerary PDF.
    Parses sections dynamically into structured Paragraphs, timeline tables,
    and a custom mobile QR code card.
    """
    # 72 points = 1 inch. Margins left/right: 54pt. Margins top/bottom: 72pt.
    doc = SimpleDocTemplate(
        filename, 
        pagesize=A4, 
        leftMargin=54, 
        rightMargin=54, 
        topMargin=72, 
        bottomMargin=72
    )
    styles = getSampleStyleSheet()
    story = []

    # --- Custom Styling Definitions ---
    title_style = ParagraphStyle(
        "TitleStyle",
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=colors.white,
        alignment=1,  # Centered
        spaceAfter=5
    )
    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=colors.HexColor("#BDC3C7"),
        alignment=1,
        spaceAfter=0
    )
    section_title_style = ParagraphStyle(
        "SectionTitleStyle",
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=colors.HexColor("#2C3E50"),
        spaceBefore=15,
        spaceAfter=5,
        leading=15
    )
    day_title_style = ParagraphStyle(
        "DayTitleStyle",
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=colors.HexColor("#1A5276"),
        leading=14
    )
    time_style = ParagraphStyle(
        "TimeStyle",
        fontName="Helvetica-Bold",
        fontSize=9.5,
        textColor=colors.HexColor("#1E90FF"),
        leading=12
    )
    spot_name_style = ParagraphStyle(
        "SpotNameStyle",
        fontName="Helvetica-Bold",
        fontSize=10.5,
        textColor=colors.HexColor("#2C3E50"),
        leading=13,
        spaceAfter=2
    )
    spot_desc_style = ParagraphStyle(
        "SpotDescStyle",
        fontName="Helvetica",
        fontSize=8.5,
        textColor=colors.HexColor("#566573"),
        leading=12
    )
    budget_card_style = ParagraphStyle(
        "BudgetCardStyle",
        fontName="Helvetica",
        fontSize=9,
        leading=12
    )
    alert_style = ParagraphStyle(
        "AlertStyle",
        fontName="Helvetica",
        fontSize=9,
        textColor=colors.HexColor("#2C3E50"),
        leading=13,
        leftIndent=10
    )
    qr_text_style = ParagraphStyle(
        "QRTextStyle",
        fontName="Helvetica",
        fontSize=9,
        textColor=colors.HexColor("#2C3E50"),
        leading=13
    )
    table_header_style = ParagraphStyle(
        "TableHeaderStyle",
        fontName="Helvetica-Bold",
        fontSize=9,
        textColor=colors.HexColor("#1A5276"),
        alignment=1
    )
    table_cell_style = ParagraphStyle(
        "TableCellStyle",
        fontName="Helvetica",
        fontSize=9,
        textColor=colors.HexColor("#2C3E50"),
        alignment=1
    )
    highlights_card_style = ParagraphStyle(
        "HighlightsCardStyle",
        fontName="Helvetica",
        fontSize=8.5,
        textColor=colors.HexColor("#5D6D7E"),
        leading=13
    )
    companion_style = ParagraphStyle(
        "CompanionStyle",
        fontName="Helvetica",
        fontSize=8.5,
        textColor=colors.HexColor("#2C3E50"),
        leading=13
    )

    lines = itinerary_text.split("\n")
    current_section = "itinerary"  # Defaults to itinerary parsing
    
    # Pre-parse Vibe for subtitle
    vibe_text = "Interactive Smart Plan"
    vibe_match = re.search(r"TRIP ITINERARY \((.*?)\)", itinerary_text, re.IGNORECASE)
    if vibe_match:
        vibe_text = vibe_match.group(1).title() + " Vibe"

    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if not line:
            i += 1
            continue

        # Check for section markers
        if "BUDGET SUMMARY" in line:
            current_section = "budget"
            i += 1
            continue
        elif "SMART ALERTS" in line:
            current_section = "alerts"
            story.append(Spacer(1, 15))
            story.append(Paragraph("SAFETY &amp; TRAVEL ALERTS", section_title_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#BDC3C7"), spaceAfter=15))
            i += 1
            continue
        elif "TRIP ITINERARY" in line:
            current_section = "itinerary"
            i += 1
            continue

        # Parse sections
        if current_section == "budget":
            if "Total:" in line:
                story.append(Spacer(1, 15))
                story.append(Paragraph("BUDGET ANALYSIS", section_title_style))
                story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#BDC3C7"), spaceAfter=15))
                
                parts = line.split("|")
                tot_val = parts[0].replace("Total:", "").strip()
                pp_val = parts[1].replace("Per Person:", "").strip() if len(parts) > 1 else ""
                
                # Render Budget Card Table
                budget_data = [
                    [
                        Paragraph(f"<font size=8 color='#7F8C8D'>TOTAL ESTIMATED BUDGET</font><br/><br/><font size=14 color='#2C3E50'><b>{tot_val}</b></font>", budget_card_style),
                        Paragraph(f"<font size=8 color='#7F8C8D'>BUDGET PER PERSON</font><br/><br/><font size=14 color='#2C3E50'><b>{pp_val}</b></font>", budget_card_style)
                    ]
                ]
                budget_table = Table(budget_data, colWidths=[240, 240])
                budget_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F8F9FA")),
                    ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#E5E7E9")),
                    ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E7E9")),
                    ('TOPPADDING', (0,0), (-1,-1), 12),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 12),
                    ('LEFTPADDING', (0,0), (-1,-1), 15),
                    ('RIGHTPADDING', (0,0), (-1,-1), 15),
                ]))
                story.append(budget_table)
                story.append(Spacer(1, 10))

        elif current_section == "alerts":
            alert_clean = escape_xml(line)
            if alert_clean:
                story.append(Paragraph(f"<font color='#E67E22'><b>!</b></font> {alert_clean}", alert_style))
                story.append(Spacer(1, 6))

        else:
            # Itinerary Parsing
            if "Travel Itinerary" in line:
                title_text = escape_xml(line)
                
                # Main Header Banner Card
                title_p = Paragraph(title_text.upper(), title_style)
                vibe_p = Paragraph(vibe_text.upper(), subtitle_style)
                banner_table = Table([[title_p], [vibe_p]], colWidths=[480])
                banner_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#2C3E50")),
                    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('TOPPADDING', (0,0), (-1,-1), 18),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 18),
                    ('LEFTPADDING', (0,0), (-1,-1), 15),
                    ('RIGHTPADDING', (0,0), (-1,-1), 15),
                ]))
                story.append(banner_table)
                story.append(Spacer(1, 20))

            elif "DAY " in line:
                day_header_text = escape_xml(line)
                story.append(Spacer(1, 10))
                
                # Day Header callout card
                day_p = Paragraph(day_header_text, day_title_style)
                day_table = Table([[day_p]], colWidths=[480])
                day_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#EBF5FB")),
                    ('LINELEFT', (0,0), (0,0), 4, colors.HexColor("#1E90FF")),
                    ('TOPPADDING', (0,0), (-1,-1), 8),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                    ('LEFTPADDING', (0,0), (-1,-1), 12),
                    ('RIGHTPADDING', (0,0), (-1,-1), 12),
                ]))
                story.append(day_table)
                story.append(Spacer(1, 10))

            elif "Local Highlights Guide:" in line:
                # Capture Day Local Highlights
                high_items = []
                for _ in range(3):
                    if i + 1 < len(lines):
                        next_line = lines[i+1].strip()
                        if next_line.startswith("•"):
                            high_items.append(escape_xml(next_line))
                            i += 1
                
                # Render highlights card
                card_html = "<b>💡 Local Insights &amp; Spots:</b><br/>"
                for item in high_items:
                    card_html += f"{item}<br/>"
                
                highlights_p = Paragraph(card_html, highlights_card_style)
                highlights_table = Table([[highlights_p]], colWidths=[480])
                highlights_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F9F9FB")),
                    ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#EAEDED")),
                    ('LINELEFT', (0,0), (0,0), 3, colors.HexColor("#A569BD")), # Purple accent line
                    ('TOPPADDING', (0,0), (-1,-1), 8),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                    ('LEFTPADDING', (0,0), (-1,-1), 12),
                    ('RIGHTPADDING', (0,0), (-1,-1), 12),
                ]))
                story.append(highlights_table)
                story.append(Spacer(1, 10))

            elif re.search(r"\d{1,2}:\d{2}\s*(?:AM|PM)\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)", line):
                # Timeline slot
                parts = line.split(":", 1)
                time_part = escape_xml(parts[0])
                spot_part = escape_xml(parts[1]) if len(parts) > 1 else ""
                
                # Fetch next line if it is a description
                desc_part = ""
                if i + 1 < len(lines):
                    next_line = lines[i+1].strip()
                    if next_line and not next_line.startswith("DAY ") and not re.search(r"\d{1,2}:\d{2}", next_line) and "BUDGET" not in next_line and "ALERTS" not in next_line and "Local Highlights" not in next_line:
                        desc_part = escape_xml(next_line)
                        i += 1  # Consume description line
                
                time_p = Paragraph(time_part, time_style)
                spot_p = Paragraph(spot_part, spot_name_style)
                desc_p = Paragraph(desc_part, spot_desc_style)
                
                timeline_data = [
                    [time_p, [spot_p, desc_p]]
                ]
                timeline_table = Table(timeline_data, colWidths=[120, 360])
                timeline_table.setStyle(TableStyle([
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                    ('TOPPADDING', (0,0), (-1,-1), 8),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                    ('LEFTPADDING', (0,0), (-1,-1), 6),
                    ('RIGHTPADDING', (0,0), (-1,-1), 6),
                    ('LINEAFTER', (0,0), (0,0), 1.5, colors.HexColor("#D5DBDB")),
                ]))
                story.append(timeline_table)
                story.append(Spacer(1, 4))
            else:
                cleaned_line = escape_xml(line)
                if cleaned_line:
                    story.append(Paragraph(cleaned_line, styles["Normal"]))
                    story.append(Spacer(1, 6))

        i += 1

    # --- Weather Outlook Table Section ---
    if weather_data and "forecast" in weather_data:
        story.append(Spacer(1, 15))
        story.append(Paragraph("WEATHER OUTLOOK", section_title_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#BDC3C7"), spaceAfter=15))
        
        weather_table_data = [
            [
                Paragraph("<b>Day / Date</b>", table_header_style),
                Paragraph("<b>Forecast Condition</b>", table_header_style),
                Paragraph("<b>Temp (Low)</b>", table_header_style),
                Paragraph("<b>Temp (High)</b>", table_header_style)
            ]
        ]
        for idx, f in enumerate(weather_data["forecast"], start=1):
            clean_date = clean_txt(f["date"])
            clean_cond = clean_txt(f["condition"])
            
            # Format label cleanly (e.g. Day 1, Day 2 or actual dates)
            date_label = f"Day {idx}" if "Day" in clean_date or not clean_date else clean_date
            weather_table_data.append([
                Paragraph(date_label, table_cell_style),
                Paragraph(clean_cond, table_cell_style),
                Paragraph(f"{f['min_temp']}°C", table_cell_style),
                Paragraph(f"{f['max_temp']}°C", table_cell_style)
            ])
            
        w_table = Table(weather_table_data, colWidths=[120, 180, 90, 90])
        w_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#EBF5FB")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#D5DBDB")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#D5DBDB")),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(w_table)
        story.append(Spacer(1, 10))

    # --- Companion Safety & Hacks Section (Solo vs Group/Family) ---
    story.append(Spacer(1, 15))
    story.append(Paragraph("CO-PILOT COMPANION GUIDE", section_title_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#BDC3C7"), spaceAfter=15))
    
    if trip_type.lower() == "solo":
        companion_color = "#E8F8F5"  # Soft mint green
        companion_border = "#2ECC71" # Green border
        companion_text = (
            "<b>🛡️ Solo Traveler Safety Hacks &amp; Social Tips:</b><br/>"
            "• <b>Live Location Sync:</b> Share your daily location link with a trusted contact.<br/>"
            "• <b>Emergency Vault Access:</b> Keep digital copies of your passport and ID in the encrypted Travel Vault.<br/>"
            "• <b>Solo-friendly Spots:</b> Visit local walking tours, boutique hostels, or heritage cafes to connect with travelers.<br/>"
            "• <b>Local Emergency Contacts:</b> Keep key local numbers noted down offline."
        )
    else:
        companion_color = "#FEF9E7"  # Soft yellow/cream
        companion_border = "#F1C40F" # Gold border
        companion_text = (
            "<b>👥 Group &amp; Family Coordination Guide:</b><br/>"
            "• <b>Assembly Points:</b> Designate a common assembly point at crowded sights in case anyone gets separated.<br/>"
            "• <b>Pacing &amp; Accessibility:</b> Itinerary slots are spaced out to accommodate toddlers and elderly travelers.<br/>"
            "• <b>Split-Trip Settlement:</b> Log group payments inside the Split-Trip tab. The system settles debts dynamically.<br/>"
            "• <b>Shared Vault Locker:</b> Store group tickets and room bookings inside the shared locker for quick offline access."
        )
        
    companion_p = Paragraph(companion_text, companion_style)
    companion_table = Table([[companion_p]], colWidths=[480])
    companion_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor(companion_color)),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor(companion_border)),
        ('LINELEFT', (0,0), (0,0), 4, colors.HexColor(companion_border)),
        ('TOPPADDING', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('LEFTPADDING', (0,0), (-1,-1), 12),
        ('RIGHTPADDING', (0,0), (-1,-1), 12),
    ]))
    story.append(companion_table)
    story.append(Spacer(1, 10))

    # --- Add QR Code Mobile Integration block ---
    temp_qr_path = "temp_qr.png"
    if qr_url:
        try:
            # Generate the QR Code image
            qr = qrcode.QRCode(version=1, box_size=4, border=2)
            qr.add_data(qr_url)
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            img.save(temp_qr_path)
            
            story.append(Spacer(1, 20))
            story.append(Paragraph("MOBILE CO-PILOT INTEGRATION", section_title_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#BDC3C7"), spaceAfter=15))
            
            qr_desc = (
                "<b>📱 Live Route Map &amp; AI Assistant:</b><br/>"
                "Scan this QR code with your mobile camera to load this interactive trip directly onto your phone! "
                "From your phone, you can view your live map coordinates, dynamically chat with the AI Travel Co-Pilot, "
                "receive alerts, and manage group expenses on the go."
            )
            
            qr_img = Image(temp_qr_path, width=100, height=100)
            desc_p = Paragraph(qr_desc, qr_text_style)
            
            qr_data = [[qr_img, desc_p]]
            qr_table = Table(qr_data, colWidths=[120, 360])
            qr_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F5EEF8")),  # Light tech-violet callout background
                ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#EBDEF0")),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('TOPPADDING', (0,0), (-1,-1), 12),
                ('BOTTOMPADDING', (0,0), (-1,-1), 12),
                ('LEFTPADDING', (0,0), (-1,-1), 15),
                ('RIGHTPADDING', (0,0), (-1,-1), 15),
            ]))
            story.append(qr_table)
            
        except Exception as e:
            print("QR code generation error:", e)

    # Build the document
    doc.build(story, canvasmaker=NumberedCanvas)

    # Clean up the temporary QR code image file
    if os.path.exists(temp_qr_path):
        try:
            os.remove(temp_qr_path)
        except Exception:
            pass
