# src/database/trips_manager.py
from src.database.db import get_connection

def save_generated_trip(user_id, destination_city, trip_duration, total_budget, trip_type, num_people, generated_text):
    """
    Saves the generated trip parameters and its itinerary text to the database.
    Returns the generated trip_id.
    """
    conn = get_connection()
    cursor = conn.cursor()
    try:
        # Insert into trips table
        cursor.execute(
            "INSERT INTO trips (user_id, destination_city, trip_duration, total_budget, trip_type, num_people) VALUES (?, ?, ?, ?, ?, ?)",
            (user_id, destination_city, trip_duration, total_budget, trip_type, num_people)
        )
        trip_id = cursor.lastrowid
        
        # Insert into itineraries table
        cursor.execute(
            "INSERT INTO itineraries (trip_id, generated_text, sustainability_score) VALUES (?, ?, ?)",
            (trip_id, generated_text, 0.0)
        )
        conn.commit()
        return trip_id
    except Exception as e:
        print("Error saving generated trip:", e)
        return None
    finally:
        conn.close()

def get_user_trips(user_id):
    """
    Fetches all trips and itineraries generated by a specific user from the database.
    """
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            SELECT t.id, t.destination_city, t.trip_duration, t.total_budget, t.trip_type, t.num_people, i.generated_text
            FROM trips t
            JOIN itineraries i ON t.id = i.trip_id
            WHERE t.user_id = ?
            ORDER BY t.id DESC
            """,
            (user_id,)
        )
        rows = cursor.fetchall()
        trips = []
        for r in rows:
            trips.append({
                "trip_id": r[0],
                "destination_city": r[1],
                "trip_duration": r[2],
                "total_budget": r[3],
                "trip_type": r[4],
                "num_people": r[5],
                "generated_text": r[6]
            })
        return trips
    except Exception as e:
        print("Error getting user trips:", e)
        return []
    finally:
        conn.close()
